apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus-stack-crds
  namespace: argocd
spec:
  project: default
  syncPolicy:
    syncOptions:
    - Replace=true
  source:
    repoURL: https://github.com/prometheus-community/helm-charts.git
    path: charts/kube-prometheus-stack/crds/
    targetRevision: kube-prometheus-stack-35.3.1
    directory:
      recurse: true
  destination:
    server: "https://kubernetes.default.svc"
    namespace: default
